Fix CTR block size error message
The format string is interpreting % bytes as %b instead of
the proper %d, resulting in an ugly error message:

ValueError: unsupported format character 'b' (0x62) at index 29