Fix unhexlify in Python 3.2
Under Python 3.2, unhexlify expects to receive a `bytes` object.
Passing it a (unicodr) `str` object causes it to raise the following
exception:

    TypeError: 'str' does not support the buffer interface